### PR TITLE
moves ss58 and crypto utilities into an util module in subp2p

### PR DESCRIPTION
**Pull request by rvalle**
This PR addresses some of #2 utility code concerns.

Relocates utility code that any package downstream implementing the authority discovery use case would need to copy and paste otherwise.

### CODE REVIEW

**Comment by rvalle** [comment]
I would consider also moving the swarm building into subp2p.

I understand that there are different behaviors that can be packed in the swarm for different use cases.

We could define/export the typical behavior sets, and offer a swarm creation entry-point where the caller selects the pre-defined behaviors or a custom if desired.

this would also be good to facilitate later #3 libp2p migration.

**Comment by rvalle** [comment]
so basically my proposal would be to move this function:

https://github.com/lexnv/subp2p-explorer/blob/f6f780eb168c26c83b04ce722f1d1efe7ae87dea/cli/src/utils.rs#L75

To the utilities, but also add the behavior as a parameter, and then add export a pre-defined set of behaviors for each use case. Kind of the recommended behaviors.

@lexnv what do you think?

**Comment by lexnv** [comment]
That sounds good to me!

Then users can pick what behavior they'd want to enable 👍

**Review by lexnv — APPROVED** [review]
Looks clean! Thanks a lot for contributing! 👍 

Moving the swarm in the util could be a separate PR or done on this if you'd like

**Comment by rvalle** [comment]
@lexnv I agree the swarm can be a separate pull request.

**Comment by rvalle** [comment]
@lexnv let me know if you need anything else from me with regards to this PR.

**Pull request merged**
